module.exports = {
  clearMocks: true,
  roots: ["<rootDir>/src"],
  preset: "ts-jest",
  testEnvironment: "jest-environment-jsdom",
  setupFilesAfterEnv: ["<rootDir>/src/config/jest.setup.ts"],
  moduleDirectories: ["node_modules", "src"],
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
  testMatch: ["**/__tests__/**/*.ts?(x)", "**/?(*.)+(spec|test).ts?(x)"],
  collectCoverage: false,
  coverageReporters: ["lcov", "text"],
  coverageDirectory: "coverage",
  coverageThreshold: {
    global: {
      statements: 95,
      branches: 95,
      functions: 95,
      lines: 95,
    },
    "./src/**/*.ts": {
      statements: 90,
      branches: 90,
      functions: 90,
      lines: 90,
    },
    "./src/**/*.tsx": {
      statements: 90,
      branches: 90,
      functions: 90,
      lines: 90,
    },
    "./src/**/*.js": {
      statements: 90,
      branches: 90,
      functions: 90,
      lines: 90,
    },
    "./src/**/*.jsx": {
      statements: 90,
      branches: 90,
      functions: 90,
      lines: 90,
    },
  },
};